import type { Lead } from "./services.types";

export const mockLeads: Lead[] = [
  {
    id: "1",
    nome: "Maria Santos",
    telefone: "+1 (305) 123-4567",
    email: "maria.santos@email.com",
    origem: "Miami, FL",
    destino: "Sao Paulo, SP",
    ultimaMensagem: "Gostaria de um orcamento para mudanca em Marco",
    dataUltimaMensagem: new Date("2024-12-21T14:30:00"),
    status: "novo",
    atendidoPorBot: true,
    valorEstimado: 8500,
    dataMudanca: "2024-03-15",
    tags: ["urgente", "apt-2-quartos"],
    prioridade: "alta",
    conversas: [
      { id: "1", texto: "Ola! Preciso de um orcamento para mudanca", remetente: "cliente", data: new Date("2024-12-21T14:25:00") },
      { id: "2", texto: "Ola! Sou a assistente virtual da ITAMOVING.", remetente: "bot", data: new Date("2024-12-21T14:25:30") },
      { id: "3", texto: "De Miami para Sao Paulo, tenho um apartamento de 2 quartos", remetente: "cliente", data: new Date("2024-12-21T14:27:00") },
    ],
  },
  {
    id: "2",
    nome: "Joao Silva",
    telefone: "+1 (407) 987-6543",
    origem: "Orlando, FL",
    destino: "Rio de Janeiro, RJ",
    ultimaMensagem: "Qual o prazo de entrega?",
    dataUltimaMensagem: new Date("2024-12-21T15:45:00"),
    status: "qualificando",
    atendidoPorBot: true,
    valorEstimado: 12000,
    prioridade: "alta",
    conversas: [{ id: "1", texto: "Qual o prazo de entrega?", remetente: "cliente", data: new Date("2024-12-21T15:45:00") }],
  },
  {
    id: "3",
    nome: "Ana Costa",
    telefone: "+1 (786) 555-1234",
    origem: "Miami, FL",
    destino: "Belo Horizonte, MG",
    ultimaMensagem: "Orçamento aprovado! Como faço o pagamento?",
    dataUltimaMensagem: new Date("2024-12-20T16:20:00"),
    status: "orcamento",
    atendidoPorBot: false,
    valorEstimado: 9500,
    prioridade: "alta",
    conversas: [{ id: "1", texto: "Orçamento aprovado!", remetente: "cliente", data: new Date("2024-12-20T16:20:00") }],
  },
];

