/** Lista dos 27 estados do Brasil (UF e nome) para uso em Selects. */
export const BRASIL_STATES = [
  { uf: "AC", nome: "Acre" },
  { uf: "AL", nome: "Alagoas" },
  { uf: "AP", nome: "Amapá" },
  { uf: "AM", nome: "Amazonas" },
  { uf: "BA", nome: "Bahia" },
  { uf: "CE", nome: "Ceará" },
  { uf: "DF", nome: "Distrito Federal" },
  { uf: "ES", nome: "Espírito Santo" },
  { uf: "GO", nome: "Goiás" },
  { uf: "MA", nome: "Maranhão" },
  { uf: "MT", nome: "Mato Grosso" },
  { uf: "MS", nome: "Mato Grosso do Sul" },
  { uf: "MG", nome: "Minas Gerais" },
  { uf: "PA", nome: "Pará" },
  { uf: "PB", nome: "Paraíba" },
  { uf: "PR", nome: "Paraná" },
  { uf: "PE", nome: "Pernambuco" },
  { uf: "PI", nome: "Piauí" },
  { uf: "RJ", nome: "Rio de Janeiro" },
  { uf: "RN", nome: "Rio Grande do Norte" },
  { uf: "RS", nome: "Rio Grande do Sul" },
  { uf: "RO", nome: "Rondônia" },
  { uf: "RR", nome: "Roraima" },
  { uf: "SC", nome: "Santa Catarina" },
  { uf: "SP", nome: "São Paulo" },
  { uf: "SE", nome: "Sergipe" },
  { uf: "TO", nome: "Tocantins" },
] as const;

// Lista dos 50 estados dos EUA (UF e nome) para uso em Selects.
export const EUA_STATES = [
  { uf: "AL", nome: "Alabama" },
  { uf: "AK", nome: "Alasca" },
  { uf: "AZ", nome: "Arizona" },
  { uf: "AR", nome: "Arkansas" },
  { uf: "CA", nome: "Califórnia" },
  { uf: "NC", nome: "Carolina do Norte" },
  { uf: "SC", nome: "Carolina do Sul" },
  { uf: "CO", nome: "Colorado" },
  { uf: "CT", nome: "Connecticut" },
  { uf: "ND", nome: "Dakota do Norte" },
  { uf: "SD", nome: "Dakota do Sul" },
  { uf: "DE", nome: "Delaware" },
  { uf: "FL", nome: "Flórida" },
  { uf: "GA", nome: "Geórgia" },
  { uf: "HI", nome: "Havaí" },
  { uf: "ID", nome: "Idaho" },
  { uf: "IL", nome: "Illinois" },
  { uf: "IN", nome: "Indiana" },
  { uf: "IA", nome: "Iowa" },
  { uf: "KS", nome: "Kansas" },
  { uf: "KY", nome: "Kentucky" },
  { uf: "LA", nome: "Louisiana" },
  { uf: "ME", nome: "Maine" },
  { uf: "MD", nome: "Maryland" },
  { uf: "MA", nome: "Massachusetts" },
  { uf: "MI", nome: "Michigan" },
  { uf: "MN", nome: "Minnesota" },
  { uf: "MS", nome: "Mississippi" },
  { uf: "MO", nome: "Missouri" },
  { uf: "MT", nome: "Montana" },
  { uf: "NE", nome: "Nebraska" },
  { uf: "NV", nome: "Nevada" },
  { uf: "NH", nome: "New Hampshire" },
  { uf: "NJ", nome: "New Jersey" },
  { uf: "NY", nome: "Nova Iorque" },
  { uf: "NM", nome: "Novo México" },
  { uf: "OH", nome: "Ohio" },
  { uf: "OK", nome: "Oklahoma" },
  { uf: "OR", nome: "Oregon" },
  { uf: "PA", nome: "Pensilvânia" },
  { uf: "RI", nome: "Rhode Island" },
  { uf: "TN", nome: "Tennessee" },
  { uf: "TX", nome: "Texas" },
  { uf: "UT", nome: "Utah" },
  { uf: "VT", nome: "Vermont" },
  { uf: "VA", nome: "Virgínia" },
  { uf: "WV", nome: "Virgínia Ocidental" },
  { uf: "WA", nome: "Washington" },
  { uf: "WI", nome: "Wisconsin" },
  { uf: "WY", nome: "Wyoming" },
] as const;